on:
  push:
    tags:
      - 'v*'
  delete:
    tags:
      - 'v*'

name: Release Branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::$version
      - name: Create branch
        if: github.event_name == 'push'
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/${{ steps.get_version.outputs.VERSION }}
      - name: Remove branch
        if: github.event_name == 'delete'
        uses: dawidd6/action-delete-branch@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: release/${{ steps.get_version.outputs.VERSION }}        
